services:
  api:
    image: ${DOCKERHUB_USERNAME}/privacy-image-guard-api:${IMAGE_TAG:-latest}
    environment:
      CV_URL: http://cv:8000
    ports:
      - "8080:8000"
    depends_on:
      - cv

  cv:
    image: ${DOCKERHUB_USERNAME}/privacy-image-guard-cv:${IMAGE_TAG:-latest}
